apiVersion: v1
kind: Service
metadata:
  name: backend-cluster-ip-service
spec:
  selector:
    app: backend-deployment
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      name: backend-port
  type: ClusterIP

