apiVersion: v1
kind: Service
metadata:
  name: backend-cluster-ip
spec:
  selector:
    app: backend-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP

