apiVersion: v1
kind: Service
metadata:
  name: frontend-cluster-ip-service
spec:
  selector:
    app: frontend-deployment
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: react-port
  type: ClusterIP

